class Program
{
    public static void Main(string[] args)
    {
        Tank t1 = new Tank("t1",0,0,55,85,true,false);
        Tank t2 = new Tank("t2",4,3,78,66,false,true);
        Tank t3 = new Tank("t3",-2,5,82,45,true,false);
        Tank t4 = new Tank("t4",-6,-2,35,72,false,true);
        Tank t5 = new Tank("t5",1,-4,0,10,true,false);
        Tank t6 = new Tank("t6", 0, 3, 5, 40, false, true);
        Tank t7 = new Tank("t7",0,-9,91,5,true, false);
        Tank t8 = new Tank("t8",4,0,77,19,false,true);
        Tank t9 = new Tank("t9",-2,0,10,56,true,false);
        Console.WriteLine(t1.gettankslocation(0,0));
        Console.WriteLine(t1.gettankshealth(55));
        Console.WriteLine(t1.gettanksname());
       t1.gettanksstype(85);
        t1.gettankdamage(55,false);
        Console.WriteLine(t1.conceallocation(true));
        Console.WriteLine(t2.gettankslocation(4,3));
        Console.WriteLine(t2.gettankshealth(78));
        Console.WriteLine(t2.gettanksname());
        t2.gettanksstype(66);
        t2.gettankdamage(78,true);
        Console.WriteLine(t2.conceallocation(false));
        Console.WriteLine(t3.gettankslocation(-2,5));
        Console.WriteLine(t3.gettankshealth(82));
        Console.WriteLine(t3.gettanksname());
        t3.gettanksstype(45);
        t3.gettankdamage(82,false);
        Console.WriteLine(t3.conceallocation(true));
        Console.WriteLine(t4.gettankslocation(-6,-2));
        Console.WriteLine(t4.gettankshealth(35));
        Console.WriteLine(t4.gettanksname());
        t4.gettanksstype(72);
        t4.gettankdamage(35,true);
        Console.WriteLine(t4.conceallocation(false));
        Console.WriteLine(t5.gettankslocation(1,-4));
        Console.WriteLine(t5.gettankshealth(0));
        Console.WriteLine(t5.gettanksname());
        t5.gettanksstype(10);
        t5.gettankdamage(0,false);
        Console.WriteLine(t5.conceallocation(true));
        Console.WriteLine(t6.gettankslocation(0,3));
        Console.WriteLine(t6.gettankshealth(5));
        Console.WriteLine(t6.gettanksname());
        t6.gettanksstype(40);
        t6.gettankdamage(5,true);
        Console.WriteLine(t6.conceallocation(false));
        Console.WriteLine(t7.gettankslocation(0, -9));
        Console.WriteLine(t7.gettankshealth(91));
        Console.WriteLine(t7.gettanksname());
        t7.gettanksstype(5);
        t7.gettankdamage(91, false);
        Console.WriteLine(t7.conceallocation(true));
        Console.WriteLine(t8.gettankslocation(4,0));
        Console.WriteLine(t8.gettankshealth(77));
        Console.WriteLine(t8.gettanksname());
        t8.gettanksstype(19);
        t8.gettankdamage(77, true);
        Console.WriteLine(t8.conceallocation(false));
        Console.WriteLine(t9.gettankslocation(-2, 0));
        Console.WriteLine(t9.gettankshealth(10));
        Console.WriteLine(t9.gettanksname());
        t9.gettanksstype(56);
        t9.gettankdamage(10, false);
        Vehicle v1 = new Vehicle("v1", 0, 0,52,83,true);
        Vehicle v2 = new Vehicle("v2",1,4,75,67,false);
        Vehicle v3 = new Vehicle("v3",-2,2,92,45,true);
        Vehicle v4 = new Vehicle("v4",-3,-5,10,35,false);
        Vehicle v5 = new Vehicle("v5",3,-2,94,58,true);
        Vehicle v6 = new Vehicle("v6",3,0,5,97,false);
        Vehicle v7 = new Vehicle("v7",-1,0,2,90,true);
        Vehicle v8 = new Vehicle("v8",0,5,12,87,false);
        Vehicle v9 = new Vehicle("v9",0,-4,100,10,true);
        Console.WriteLine(v1.getvehicleslocation(0,0));
        Console.WriteLine(v1.getvehileshealth(52));
        Console.WriteLine(v1.getvehiclesname());
        v1.getvehiclestype(83);
        v1.getvehicledamage(52,true);
        Console.WriteLine(v2.getvehicleslocation(1, 4));
        Console.WriteLine(v2.getvehileshealth(75));
        Console.WriteLine(v2.getvehiclesname());
        v2.getvehiclestype(67);
        v2.getvehicledamage(75, false);
        Console.WriteLine(v3.getvehicleslocation(-2,2));
        Console.WriteLine(v3.getvehileshealth(92));
        Console.WriteLine(v3.getvehiclesname());
        v3.getvehiclestype(45);
        v3.getvehicledamage(92, true);
        Console.WriteLine(v4.getvehicleslocation(-3, -5));
        Console.WriteLine(v4.getvehileshealth(10));
        Console.WriteLine(v4.getvehiclesname());
        v4.getvehiclestype(35);
        v4.getvehicledamage(10, false);
        Console.WriteLine(v5.getvehicleslocation(3, -2));
        Console.WriteLine(v5.getvehileshealth(94));
        Console.WriteLine(v5.getvehiclesname());
        v5.getvehiclestype(58);
        v5.getvehicledamage(94, true);
        Console.WriteLine(v6.getvehicleslocation(3, 0));
        Console.WriteLine(v6.getvehileshealth(5));
        Console.WriteLine(v6.getvehiclesname());
        v6.getvehiclestype(97);
        v6.getvehicledamage(5,false);
        Console.WriteLine(v7.getvehicleslocation(0, 5));
        Console.WriteLine(v7.getvehileshealth(2));
        Console.WriteLine(v7.getvehiclesname());
        v7.getvehiclestype(90);
        v7.getvehicledamage(2, true);
        Console.WriteLine(v8.getvehicleslocation(-1, 0));
        Console.WriteLine(v8.getvehileshealth(12));
        Console.WriteLine(v8.getvehiclesname());
        v8.getvehiclestype(87);
        v8.getvehicledamage(12,false);
        Console.WriteLine(v9.getvehicleslocation(0, -4));
        Console.WriteLine(v9.getvehileshealth(100));
        Console.WriteLine(v9.getvehiclesname());
        v9.getvehiclestype(10);
        v9.getvehicledamage(100, true);
        Officer o1 = new Officer("A",1,55,0,0,true,"Walk");
        Officer o2 = new Officer("B",2,-10,0,1,false,"Run");
        Officer o3 = new Officer("C",3,2,0,-1,true,"Jump");
        Officer o4 = new Officer("D",4,5,1,0,false,"Sleep");
        Officer o5 = new Officer("E",5,0,-1,0,true,"Eat");
        Officer o6 = new Officer("F",6,45,1,1,false,"Sneezing");
        Officer o7 = new Officer("G",7,33,-1,4,true,"Cut");
        Officer o8 = new Officer("H",8,10,-2,-3,false,"Press");
        Officer o9 = new Officer("I",9,0,1,-8,true,"Cook");
        Console.WriteLine(o1.getofficerslocation(0,0));
        Console.WriteLine(o1.getofficersrsname());
        Console.WriteLine(o1.GetOfficcerRank(1));
        Console.WriteLine(o1.getofficershealth(55));
        o1.getdamage(55,true);
        Console.WriteLine(o1.givingorder("Walk"));
        Console.WriteLine(o2.getofficerslocation(0, 1));
        Console.WriteLine(o2.getofficersrsname());
        Console.WriteLine(o2.GetOfficcerRank(2));
        Console.WriteLine(o2.getofficershealth(-10));
        o2.getdamage(-10, false);
        Console.WriteLine(o2.givingorder("Run"));
        Console.WriteLine(o3.getofficerslocation(0, -1));
        Console.WriteLine(o3.getofficersrsname());
        Console.WriteLine(o3.GetOfficcerRank(3));
        Console.WriteLine(o3.getofficershealth(2));
        o3.getdamage(2, true);
        Console.WriteLine(o3.givingorder("Jump"));
        Console.WriteLine(o4.getofficerslocation(1, 0));
        Console.WriteLine(o4.getofficersrsname());
        Console.WriteLine(o4.GetOfficcerRank(4));
        Console.WriteLine(o4.getofficershealth(5));
        o4.getdamage(5, false);
        Console.WriteLine(o5.givingorder("Eat"));
        Console.WriteLine(o5.getofficerslocation(-1, 0));
        Console.WriteLine(o5.getofficersrsname());
        Console.WriteLine(o5.GetOfficcerRank(5));
        Console.WriteLine(o5.getofficershealth(0));
        o5.getdamage(0, true);
        Console.WriteLine(o5.givingorder("Eat"));
        Console.WriteLine(o6.getofficerslocation(1, 1));
        Console.WriteLine(o6.getofficersrsname());
        Console.WriteLine(o6.GetOfficcerRank(6));
        Console.WriteLine(o6.getofficershealth(45));
        o6.getdamage(45, false);
        Console.WriteLine(o6.givingorder("Sneezing"));
        Console.WriteLine(o7.getofficerslocation(-1, 4));
        Console.WriteLine(o7.getofficersrsname());
        Console.WriteLine(o7.GetOfficcerRank(7));
        Console.WriteLine(o7.getofficershealth(33));
        o7.getdamage(33, true);
        Console.WriteLine(o7.givingorder("Cut"));
        Console.WriteLine(o8.getofficerslocation(-2, -3));
        Console.WriteLine(o8.getofficersrsname());
        Console.WriteLine(o8.GetOfficcerRank(8));
        Console.WriteLine(o8.getofficershealth(10));
        o8.getdamage(10, false);
        Console.WriteLine(o8.givingorder("Press"));
        Console.WriteLine(o9.getofficerslocation(1, -8));
        Console.WriteLine(o9.getofficersrsname());
        Console.WriteLine(o9.GetOfficcerRank(9));
        Console.WriteLine(o9.getofficershealth(0));
        o9.getdamage(0, true);
        Console.WriteLine(o9.givingorder("Cook"));
        Soldier s1 = new Soldier("A",1,55,0,0,true);
        Soldier s2 = new Soldier("B",2,10,1,0,false);
        Soldier s3 = new Soldier("C", 3, 67, -1, 0, true);
        Soldier s4 = new Soldier("D", 4, 100, 0, 1, false);
        Soldier s5 = new Soldier("E", 5, 20, 0, -1, true);
        Soldier s6 = new Soldier("F", 6, 50, 1, 1, false);
        Soldier s7 = new Soldier("G", 7, 87, -1, 1, true);
        Soldier s8 = new Soldier("H", 8, 56, -1, -1, false);
        Soldier s9 = new Soldier("I", 9, 34, 1, -1, true);
        Soldier s10 = new Soldier("J", 10, 46, -1, 4, false);
        Console.WriteLine(s1.getlocation(0,0));
        Console.WriteLine(s1.getsoldiersname());
        Console.WriteLine(s1.GetSoldierRank(1));
        Console.WriteLine(s1.getsoldiershealth(55));
        s1.getdamage(55,true);
        Console.WriteLine(s2.getlocation(1, 0));
        Console.WriteLine(s2.getsoldiersname());
        Console.WriteLine(s2.GetSoldierRank(2));
        Console.WriteLine(s2.getsoldiershealth(10));
        s2.getdamage(10, false);
        Console.WriteLine(s3.getlocation(-1, 0));
        Console.WriteLine(s3.getsoldiersname());
        Console.WriteLine(s3.GetSoldierRank(3));
        Console.WriteLine(s3.getsoldiershealth(67));
        s3.getdamage(67, true);
        Console.WriteLine(s4.getlocation(0, 1));
        Console.WriteLine(s4.getsoldiersname());
        Console.WriteLine(s4.GetSoldierRank(4));
        Console.WriteLine(s4.getsoldiershealth(100));
        s4.getdamage(100, false);
        Console.WriteLine(s5.getlocation(0, -1));
        Console.WriteLine(s5.getsoldiersname());
        Console.WriteLine(s5.GetSoldierRank(5));
        Console.WriteLine(s5.getsoldiershealth(20));
        s5.getdamage(20, true);
        Console.WriteLine(s6.getlocation(1, 1));
        Console.WriteLine(s6.getsoldiersname());
        Console.WriteLine(s6.GetSoldierRank(6));
        Console.WriteLine(s6.getsoldiershealth(50));
        s6.getdamage(50, false);
        Console.WriteLine(s7.getlocation(-1, 1));
        Console.WriteLine(s7.getsoldiersname());
        Console.WriteLine(s7.GetSoldierRank(7));
        Console.WriteLine(s7.getsoldiershealth(87));
        s7.getdamage(87, true);
        Console.WriteLine(s8.getlocation(-1, -1));
        Console.WriteLine(s8.getsoldiersname());
        Console.WriteLine(s8.GetSoldierRank(8));
        Console.WriteLine(s8.getsoldiershealth(56));
        s8.getdamage(56, false);
        Console.WriteLine(s9.getlocation(1, -1));
        Console.WriteLine(s9.getsoldiersname());
        Console.WriteLine(s9.GetSoldierRank(9));
        Console.WriteLine(s9.getsoldiershealth(34));
        s9.getdamage(34, true);
        Console.WriteLine(s10.getlocation(-1, 4));
        Console.WriteLine(s10.getsoldiersname());
        Console.WriteLine(s10.GetSoldierRank(10));
        Console.WriteLine(s10.getsoldiershealth(46));
        s10.getdamage(46, false);
    }
}
